# Generated by Django 5.1.6 on 2025-04-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwallet",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
