# Generated by Django 5.1.6 on 2025-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdenapp", "0002_propertyimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="provision",
            field=models.CharField(
                choices=[("Rent", "Rent"), ("Lease", "Lease"), ("Sale", "Sale")],
                default="rent",
                max_length=10,
            ),
        ),
    ]
