# Generated by Django 5.1.6 on 2025-03-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdenapp", "0004_alter_propertyimage_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Apartment", "Apartment"),
                            ("Residence", "Residence"),
                            ("Unit", "Unit"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "categories",
            },
        ),
        migrations.RenameField(
            model_name="property",
            old_name="isPairToPair",
            new_name="isPeerToPeer",
        ),
        migrations.AlterField(
            model_name="property",
            name="typeChoice",
            field=models.CharField(
                choices=[
                    ("studio", "Studio"),
                    ("1-bedroom", "1-Bedroom"),
                    ("2-bedroom", "2-Bedroom"),
                    ("3-bedroom", "3-Bedroom"),
                    ("pent-house", "Pent-House"),
                    ("single-family-home", "Single-Family-Home"),
                    ("town-house", "Town-House"),
                    ("condominium", "Condominium"),
                    ("duplex", "Duplex"),
                    ("villa", "Villa"),
                    ("luxury-apartment", "Luxury-Apartment"),
                    ("estate-home", "Estate-Home"),
                    ("mansion", "Mansion"),
                    ("private-villa", "Private-Villa"),
                    ("pent-house-suite", "Pent-House-Suite"),
                ],
                default="",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bdenapp.category",
            ),
        ),
    ]
