# Generated by Django 5.1.6 on 2025-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdenapp", "0011_alter_property_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_merchant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
    ]
