# Generated by Django 5.1.6 on 2025-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdenapp", "0012_userprofile_is_merchant_userprofile_is_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="images",
            field=models.FileField(blank=True, null=True, upload_to="more_pictures/"),
        ),
    ]
