# Generated by Django 5.1.6 on 2025-04-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdenapp", "0014_property_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(max_length=5),
        ),
    ]
