# Generated by Django 5.1.6 on 2025-04-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdenapp", "0016_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.CharField(max_length=500),
        ),
    ]
