# Generated by Django 5.1.6 on 2025-04-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bdenapp", "0017_alter_review_review_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
